backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  commit_messages:
    create: Create {{collection}} "{{slug}}"
    update: Update {{collection}} "{{slug}}"
    delete: Delete {{collection}} "{{slug}}"
    uploadMedia: Upload "{{path}}"
    deleteMedia: Delete "{{path}}"

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

site_url: https://durhamsacredharp.co.uk
logo_url: /assets/images/dsh_new_share_image.png

media_folder: "assets/images" # Media files will be stored in the repo under images/uploads

collections:
  - label: "Sections Text"
    name: "sections_text"
    files:
      - label: "Introduction"
        name: "Introduction"
        file: "_data/sections_text/introduction.json"
        fields:
          - {label: tagline, name: tagline, widget: string}
          - {label: text, name: text, widget: markdown}

      - label: "Next Singings"
        name: "Next Singings"
        file: "_data/sections_text/next_singings.json"
        fields:
          - label: "Show Special Announcement?"
            name: "showSpecialAnnouncement"
            widget: "select"
            default: "Yes"
            options:
              - { label: "Yes", value: "true" }
              - { label: "No", value: "false" }
          - {label: specialAnnouncement, name: specialAnnouncement, widget: markdown}
          - {label: text, name: text, widget: markdown}

      - label: "End of Introduction"
        name: "end_introduction"
        file: "_data/sections_text/end_introduction.json"
        fields:
          - {label: Text, name: text, widget: markdown}

      - label: "Venue"
        name: "Venue"
        file: "_data/sections_text/venue.json"
        fields:
          - {label: sectionTitle, name: sectionTitle, widget: string}
          - {label: venueAddress, name: venueAddress, widget: markdown}
          - {label: venueDescription, name: venueDescription, widget: markdown}
          - {label: clickMapsInstruction, name: clickMapsInstruction, widget: string}
          - {label: GoogleMapsLink, name: GoogleMapsLink, widget: string}
          - {label: GoogleMapsImage, name: GoogleMapsImage, widget: image, allow_multiple: false}
          - {label: GoogleMapsImageAltText, name: GoogleMapsImageAltText, widget: string}
          - {label: GoogleMapsLegal, name: GoogleMapsLegal, widget: markdown}

      - label: "Contact Us"
        name: "Contact Us"
        file: "_data/sections_text/contact.json"
        fields:
          - {label: sectionTitle, name: sectionTitle, widget: string}
          - {label: emailUsText, name: emailUsText, widget: string}
          - {label: tweetUsText, name: tweetUsText, widget: string}

      - label: "More Information"
        name: "More Information"
        file: "_data/sections_text/more_information.json"
        fields:
          - {label: sectionTitle, name: sectionTitle, widget: string}
          - {label: text, name: text, widget: markdown}