backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  commit_messages:
    create: Create {{collection}} "{{slug}}"
    update: Update {{collection}} "{{slug}}"
    delete: Delete {{collection}} "{{slug}}"
    uploadMedia: Upload "{{path}}"
    deleteMedia: Delete "{{path}}"

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

site_url: https://durhamsacredharp.co.uk
logo_url: /assets/images/dsh_new_share_image.png

media_folder: "assets/images" # Media files will be stored in the repo under images/uploads

collections:
  - label: "Sections Text"
    name: "sections_text"
    files:
      - label: "Introduction"
        name: "Introduction"
        file: "_data/sections_text/introduction.json"
        fields:
          - {label: tagline, name: tagline, widget: string}
          - {label: second_tagline, name: second_tagline, widget: string}
          - {label: text, name: text, widget: markdown}

      - label: "Next Singings"
        name: "Next Singings"
        file: "_data/sections_text/next_singings.json"
        fields:
          - label: "Show Special Announcement?"
            name: "showSpecialAnnouncement"
            widget: "select"
            default: "yes"
            options:
              - { label: "Yes", value: "yes" }
              - { label: "No", value: "no" }
          - {label: Special Announcement End Date, name: specialAnnouncementEndDate, widget: date, format: "x", description: When is the last day you want the special announcement to show?}
          - {label: Special Announcement Text, name: specialAnnouncement, widget: markdown}
          - {label: text, name: text, widget: markdown}

      - label: "End of Introduction"
        name: "end_introduction"
        file: "_data/sections_text/end_introduction.json"
        fields:
          - {label: Text, name: text, widget: markdown}

      - label: "Venue"
        name: "Venue"
        file: "_data/sections_text/venue.json"
        fields:
          - {label: section Title, name: sectionTitle, widget: string}
          - {label: venue Address, name: venueAddress, widget: markdown}
          - {label: venue Description, name: venueDescription, widget: markdown}
          - {label: click Maps Instruction, name: clickMapsInstruction, widget: string}
          - {label: Google Maps Link, name: GoogleMapsLink, widget: string}
          - {label: Google Maps Image, name: GoogleMapsImage, widget: image, allow_multiple: false}
          - {label: Google Maps Image Alt Text, name: GoogleMapsImageAltText, widget: string}
          - {label: Google Maps Legal, name: GoogleMapsLegal, widget: markdown}

      - label: "Contact Us"
        name: "Contact Us"
        file: "_data/sections_text/contact.json"
        fields:
          - {label: section Title, name: sectionTitle, widget: string}
          - {label: email Us Text, name: emailUsText, widget: string}
          - {label: tweet Us Text, name: tweetUsText, widget: string}

      - label: "More Information"
        name: "More Information"
        file: "_data/sections_text/more_information.json"
        fields:
          - {label: section Title, name: sectionTitle, widget: string}
          - {label: text, name: text, widget: markdown}
