name: Netlify Deploy

on:
  schedule:
  - cron: "1 0 * * SUN"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Netlify Hook
      run: curl -X POST ${{ secrets.netlify_build_url }}
